### ISSUE TITLE
Not registered on bower registry

### ISSUE THREAD

**Issue by cyrbon** [mikemckibben/purescript-console-foreign#1]
This package is awesome and works as intended. However, currently it's difficult to install because it's not registered in the bower registry, so one can't `bower install purescript-console-foreign` despite the`README.md` saying it's the preferred method of installation :(

**Comment by mikemckibben** [comment]
Thanks for the feedback. I'm glad you find this package useful. I'll look into what's involved in publishing to pursuit... I was originally waiting to see how the new psc-package shakes out.

**Comment by mikemckibben** [comment]
Published to pursuit/bower. Closing.
